### ISSUE TITLE
Post poll to forum

### ISSUE THREAD

**Issue by IRus** [Heapy/kotbot#41]
1. Send poll to bot
2. Reply to this poll with `/post_poll`
3. Bot will send new poll to channel

**Comment by r4zzz4k** [comment]
Or just `/post`: the bot will see the type of the replied-to message anyway.

But what are use-cases for polls in forum?

**Comment by IRus** [comment]
> Or just `/post`: the bot will see the type of the replied-to message anyway.
> 
> But what are use-cases for polls in forum?

Different user polls, like tabs vs spaces, ternary operator yes or no, do you use kotlin for backend or mobile, etc.
Since threads, likely, will have more visibility it makes sense to start doing polls
