### ISSUE TITLE
Optional notification to users when they get replies to forum posts

### ISSUE THREAD

**Issue by r4zzz4k** [Heapy/kotbot#42]
As of now, you don't know anything about your forum post, and you can't subscribe to updates. Of course when you start participating, you'll get notifications on direct replies to you. But it's very easy to forget about the question you've posted and get back to it much later.

We should enable periodic notifications about post comments with the flow as follows:
1. User creates a `/post`.
2. Bot sends a link to the post to the user.
3. If any replies to the post appear, bot sends a notification to the user and snoozes this post for some delay (e.g. 15 minutes).
4. If any replies occur during snooze period, nothing happens. Replies by topic starter can probably reset snooze as those show the user is still actively monitoring replies.
5. If the reply appears after snooze is over, bot sends a notification to the user.
6. At some point user disables notifications for specific post in case she already got the answer she needed. For example, this can be implemented via inline keyboard button on the notification.

User should also be able to enable / disable notifications globally and change snooze delay, so that the forum workflow fits her messenger usage best.

Other users should be able to also subscribe to the post replies. This may help if you see the question you're also interested in.

Some types of posts (like polls) may need different strategies for notifications, this is a thing to consider but is out of scope for this issue.

**Comment by IRus** [comment]
Now, topics in Telegram have native notifications.
