### ISSUE TITLE
Add rule to delete single emoji messages

### ISSUE THREAD

**Issue by IRus** [Heapy/kotbot#7]
Like this

<img width="680" alt="Screen Shot 2019-08-12 at 4 00 15 PM" src="https://user-images.githubusercontent.com/493656/62866749-4cfd9f80-bd1a-11e9-83b2-fc6139411650.png">

**Comment by r4zzz4k** [comment]
Large emoji can be turned on and off in settings. Maybe it's okay to leave them be for people to decide themselves whether they want to see animations or not? To me it feels that single emoji could sometimes are meaningful enough to be represented as a whole message.

**Comment by IRus** [comment]
With #27 it's becomes less important to control each message, since they will be spreader over threads.
